### ISSUE TITLE
token得请求次数限制问题？

### ISSUE THREAD

**Issue by WangJunZzz** [netnr/Netnr.Login#3]
比如在微信access_token每天上限是2000,这个好像没处理。

**Comment by netnr** [comment]
实现的接口查询的结果要不要做缓存，看自己情况

**Comment by WangJunZzz** [comment]
是得，因为我有看的微信中得获取用户信息得源码，发现没有做这个，我之前有想写一个微信得sdk，对于保存token打算保存在redis中，不知道有其他得方式没。

**Comment by netnr** [comment]
最简单的方式，直接用缓存

**Comment by WangJunZzz** [comment]
EN
