### ISSUE TITLE
微信第三方登录在PC和手机上应该使用不同的url

### ISSUE THREAD

**Issue by LiveIsLive** [netnr/Netnr.Login#4]
[https://my.oschina.net/giegie/blog/735757](https://my.oschina.net/giegie/blog/735757)

现在使用 WeChat.AuthorizationHref 生成的是PC的登录url，但在手机上无法打开这个url在同一台手机上扫码登陆。
建议最好能识别当前浏览器环境是手机还是PC，自动生成对应的url。如果不可以的话，最好可以增加参数或者方法用来生成手机的登录url。

**Comment by netnr** [comment]
可以的

**Comment by netnr** [comment]
看了一下，微信官网移动端登录仅提供 Android、IOS 客户端登录，所以不做改变
如果通过你给出的文章提到的接口可以实现，那么请你自己构建登录跳转链接
