### ISSUE TITLE
支付宝登陆获取access_token返回null

### ISSUE THREAD

**Issue by LiveIsLive** [netnr/Netnr.Login#5]
根据例子在回调页面执行
```
var tokenEntity = AliPay.AccessToken(new AliPay_AccessToken_RequestEntity
{
	code = authorizeResult.auth_code
});
```
获取access_token的时候，AliPay.AccessToken返回null，根据源代码分析是由于 AliPay_AccessToken_RequestEntity 对象的 sign属性值为null导致，但查找所有源代码和调用例子，都找不到有其他地方引用过 AliPay_AccessToken_RequestEntity.sign属性。

**Comment by netnr** [comment]
请把内容和代码分开并使用代码片段

**Comment by LiveIsLive** [comment]
已使用代码片段分割代码和内容。

**Comment by netnr** [comment]
已经修复更新
