### ISSUE TITLE
能不能增加对微信公众号登录的支持？

### ISSUE THREAD

**Issue by LiveIsLive** [netnr/Netnr.Login#6]
据我所知，微信公众号登录和现在的微信开放平台登录是完全一样的，只是有两个变量值有区别：
1：微信公众号登录API_Authorize这个变量的值是https://open.weixin.qq.com/connect/oauth2/authorize
2：微信公众号登录Scope这个变量的值是snsapi_userinfo
其余代码完全一样没区别。

**Comment by netnr** [comment]
[Netnr.Login.5.1.0-rc.1.zip](https://github.com/netnr/Netnr.Login/files/9590381/Netnr.Login.5.1.0-rc.1.zip)

试试，记得反馈，如果有微信开放平台也帮忙测试一下

（修复：获取个人信息漏了）

**Comment by LiveIsLive** [comment]
@netnr 
刚刚试过微信公众号登录模块可以正常使用，希望可以更新Nuget
